director_uuid: "<%= `bosh --target lite status --uuid`.strip %>"

name: etcd

releases:
- name: etcd
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: etcd_z1
  instances: 3
  networks:
  - name: etcd
  azs: [eu-west-1c]
  jobs:
  - release: etcd
    name: etcd
    properties:
      etcd:
        peer_require_ssl: false
        require_ssl: false
        heartbeat_interval_in_milliseconds: 50
  stemcell: trusty
  vm_type: m3.xlarge
  persistent_disk_type: 5120

update:
  canary_watch_time: 1000-180000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-180000
  canaries: 1